# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("accessibility.typeaheadfind.flashBar", 0);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1484838249);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1484838369);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1484841489);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1484838129);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1484838009);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1484838489);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.frecency_experiment", 4);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1482767202);
user_pref("browser.laterrun.bookkeeping.sessionCount", 4);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 40);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 8);
user_pref("browser.preferences.advanced.selectedTabIndex", 4);
user_pref("browser.reader.detectedFirstArticle", true);
user_pref("browser.safebrowsing.provider.google.lastupdatetime", "1484841229864");
user_pref("browser.safebrowsing.provider.google.nextupdatetime", "1484842943864");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1484841382624");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1484844982624");
user_pref("browser.search.countryCode", "FR");
user_pref("browser.search.region", "FR");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20161017194814");
user_pref("browser.slowStartup.averageTime", 18000);
user_pref("browser.slowStartup.samples", 4);
user_pref("browser.startup.homepage_override.buildID", "20161017194814");
user_pref("browser.startup.homepage_override.mstone", "51.0a2");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"PanelUI-contents\":[\"edit-controls\",\"zoom-controls\",\"new-window-button\",\"e10s-button\",\"privatebrowsing-button\",\"save-page-button\",\"print-button\",\"history-panelmenu\",\"fullscreen-button\",\"find-button\",\"preferences-button\",\"add-ons-button\",\"sync-button\"],\"addon-bar\":[\"addonbar-closebutton\",\"status-bar\"],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"urlbar-container\",\"search-container\",\"developer-button\",\"bookmarks-menu-button\",\"downloads-button\",\"home-button\",\"webide-button\",\"pocket-button\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"toolbar-menubar\":[\"menubar-items\"]},\"seen\":[\"pocket-button\",\"developer-button\",\"webide-button\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\",\"PanelUI-contents\",\"addon-bar\"],\"currentVersion\":6,\"newElementCount\":0}");
user_pref("browser.urlbar.daysBeforeHidingSuggestionsPrompt", 3);
user_pref("browser.urlbar.lastSuggestionsPromptDate", 20170119);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1482767264309");
user_pref("datareporting.sessions.current.activeTicks", 45);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 5790);
user_pref("datareporting.sessions.current.main", 60);
user_pref("datareporting.sessions.current.sessionRestored", 5351);
user_pref("datareporting.sessions.current.startTime", "1484837766877");
user_pref("datareporting.sessions.current.totalTime", 3794);
user_pref("datareporting.sessions.currentIndex", 3);
user_pref("datareporting.sessions.previous.0", "{\"s\":1482767161521,\"a\":22,\"t\":3579,\"c\":true,\"m\":37940,\"fp\":42916,\"sr\":42775}");
user_pref("datareporting.sessions.previous.1", "{\"s\":1484306377260,\"a\":1,\"t\":23,\"c\":true,\"m\":6031,\"fp\":15813,\"sr\":15547}");
user_pref("datareporting.sessions.previous.2", "{\"s\":1484306431793,\"a\":0,\"t\":14,\"c\":false,\"m\":111,\"fp\":9294,\"sr\":8916}");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("e10s.rollout.cohort", "unsupportedChannel");
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.pingCountTotal", 3);
user_pref("extensions.blocklist.pingCountVersion", 3);
user_pref("extensions.bootstrappedAddons", "{\"flyweb@mozilla.org\":{\"version\":\"1.0.0\",\"type\":\"extension\",\"descriptor\":\"/usr/lib/firefox/browser/features/flyweb@mozilla.org.xpi\",\"multiprocessCompatible\":true,\"runInSafeMode\":true,\"dependencies\":[]},\"firefox@getpocket.com\":{\"version\":\"1.0.5\",\"type\":\"extension\",\"descriptor\":\"/usr/lib/firefox/browser/features/firefox@getpocket.com.xpi\",\"multiprocessCompatible\":true,\"runInSafeMode\":true,\"dependencies\":[]},\"e10srollout@mozilla.org\":{\"version\":\"1.4\",\"type\":\"extension\",\"descriptor\":\"/usr/lib/firefox/browser/features/e10srollout@mozilla.org.xpi\",\"multiprocessCompatible\":true,\"runInSafeMode\":true,\"dependencies\":[]},\"formautofill@mozilla.org\":{\"version\":\"1.0\",\"type\":\"extension\",\"descriptor\":\"/usr/lib/firefox/browser/features/formautofill@mozilla.org.xpi\",\"multiprocessCompatible\":true,\"runInSafeMode\":true,\"dependencies\":[]},\"webcompat@mozilla.org\":{\"version\":\"1.0\",\"type\":\"extension\",\"descriptor\":\"/usr/lib/firefox/browser/features/webcompat@mozilla.org.xpi\",\"multiprocessCompatible\":true,\"runInSafeMode\":true,\"dependencies\":[]},\"langpack-en-GB@firefox.mozilla.org\":{\"version\":\"51.0a2\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"multiprocessCompatible\":false,\"runInSafeMode\":false,\"dependencies\":[]},\"langpack-en-ZA@firefox.mozilla.org\":{\"version\":\"51.0a2\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\",\"multiprocessCompatible\":false,\"runInSafeMode\":false,\"dependencies\":[]},\"langpack-fr@firefox.mozilla.org\":{\"version\":\"51.0a2\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-fr@firefox.mozilla.org.xpi\",\"multiprocessCompatible\":false,\"runInSafeMode\":false,\"dependencies\":[]}}");
user_pref("extensions.databaseSchema", 18);
user_pref("extensions.e10s.rollout.hasAddon", false);
user_pref("extensions.e10sBlockedByAddons", true);
user_pref("extensions.enabledAddons", "ubufox%40ubuntu.com:3.2,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:51.0a2");
user_pref("extensions.getAddons.cache.lastUpdate", 1484838250);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.hotfix.lastVersion", "20160826.01");
user_pref("extensions.lastAppVersion", "51.0a2");
user_pref("extensions.lastPlatformVersion", "51.0a2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.xpiState", "{\"app-system-defaults\":{\"flyweb@mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/features/flyweb@mozilla.org.xpi\",\"e\":true,\"v\":\"1.0.0\",\"st\":1476738273000},\"firefox@getpocket.com\":{\"d\":\"/usr/lib/firefox/browser/features/firefox@getpocket.com.xpi\",\"e\":true,\"v\":\"1.0.5\",\"st\":1476738273000},\"e10srollout@mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/features/e10srollout@mozilla.org.xpi\",\"e\":true,\"v\":\"1.4\",\"st\":1476738273000},\"formautofill@mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/features/formautofill@mozilla.org.xpi\",\"e\":true,\"v\":\"1.0\",\"st\":1476738273000},\"webcompat@mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/features/webcompat@mozilla.org.xpi\",\"e\":true,\"v\":\"1.0\",\"st\":1476738273000}},\"app-global\":{\"langpack-en-GB@firefox.mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"e\":true,\"v\":\"51.0a2\",\"st\":1476738479000},\"langpack-en-ZA@firefox.mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\",\"e\":true,\"v\":\"51.0a2\",\"st\":1476738479000},\"langpack-fr@firefox.mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/extensions/langpack-fr@firefox.mozilla.org.xpi\",\"e\":true,\"v\":\"51.0a2\",\"st\":1476738490000},\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi\",\"e\":true,\"v\":\"51.0a2\",\"st\":1476738273000}},\"app-system-share\":{\"ubufox@ubuntu.com\":{\"d\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/ubufox@ubuntu.com.xpi\",\"e\":true,\"v\":\"3.2\",\"st\":1442597402000}}}");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1482767265);
user_pref("media.gmp-gmpopenh264.version", "1.6");
user_pref("media.gmp-manager.buildID", "20161017194814");
user_pref("media.gmp-manager.lastCheck", 1484837832);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 122334);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("security.disable_button.openCertManager", false);
user_pref("security.disable_button.openDeviceManager", false);
user_pref("security.entreprise_root.enabled", true);
user_pref("services.blocklist.addons.checked", 1484837912);
user_pref("services.blocklist.clock_skew_seconds", 457);
user_pref("services.blocklist.gfx.checked", 1484837912);
user_pref("services.blocklist.last_etag", "\"1482343886415\"");
user_pref("services.blocklist.last_update_seconds", 1484837912);
user_pref("services.blocklist.onecrl.checked", 1482344027);
user_pref("services.blocklist.plugins.checked", 1484837912);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1484837766);
user_pref("toolkit.telemetry.cachedClientID", "f395cc54-ee91-4102-ac22-0e9e5e6f9519");
user_pref("toolkit.telemetry.previousBuildID", "20161017194814");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
