type: mysql
name: wp_maestro
backup_path: wp_maestro_*.sql
backup_local: true
update: |
  UPDATE core_config_data SET value='http://wp-maestro.username.jetpulp.dev/' WHERE value='http://www.wp-maestro.com/';
  UPDATE core_config_data SET value='1' WHERE path='dev/log/active';
  UPDATE core_config_data SET value='1' WHERE path='dev/template/allow_symlink';