DROP TABLE IF EXISTS  `cri_matiere`;

CREATE TABLE `cri_matiere` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `code` varchar(5) COLLATE utf8_unicode_ci NOT NULL,
  `label` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `short_label` varchar(20) COLLATE utf8_unicode_ci NOT NULL,
  `displayed` tinyint(1) NOT NULL DEFAULT '0',
  `picto` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UX_CODE` (`code`)
) ENGINE=InnoDB AUTO_INCREMENT=25 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


INSERT INTO `cri_matiere` (`id`, `code`, `label`, `short_label`, `displayed`, `picto`) VALUES
(1, 'A',	'Famille', 'Fam', 1, 'wp-content/uploads/matieres/picto/CRIDON-PICTOS-BD-Famille.png'),
(2, 'B', 'Commercial', 'Comm', 1, 'wp-content/uploads/matieres/picto/CRIDON-PICTOS-BD-Commercial.png'),
(3, 'C', 'Société', 'Sté', 1, ''),
(4, 'D', 'Construction', 'Const', 1, 'wp-content/uploads/matieres/picto/CRIDON-PICTOS-BD-Construction.png'),
(5, 'E', 'Fiscalité', 'Fisc', 1, 'wp-content/uploads/matieres/picto/CRIDON-PICTOS-BD-Fiscal.png'),
(6, 'F', 'Droit international privé', 'DIP', 1, 'wp-content/uploads/matieres/picto/CRIDON-PICTOS-BD-Prive.png'),
(7, 'G', 'Rural', 'Rural', 1, 'wp-content/uploads/matieres/picto/CRIDON-PICTOS-BD-Rural.png'),
(8, 'H', 'Social-Travail', 'Social', 1, 'wp-content/uploads/matieres/picto/CRIDON-PICTOS-BD-Social.png'),
(9, 'K', 'Documentation', 'Docu', 1, ''),
(10, 'L', 'Droit administratif', 'Admin', 1, ''),
(11, 'O', 'Obligations', 'Oblig', 1, 'wp-content/uploads/matieres/picto/CRIDON-PICTOS-BD-Obligations.png'),
(12, 'P', 'Procédure', 'Proc', 1, 'wp-content/uploads/matieres/picto/CRIDON-PICTOS-BD-Procedure.png'),
(13, 'I', 'Environnement', 'Envir', 1, 'wp-content/uploads/matieres/picto/CRIDON-PICTOS-BD-Environnement.png'),
(14, 'X', 'Expertise Transversale', 'Transvers', 1, 'wp-content/uploads/matieres/picto/2_CRIDON-PICTOS-BD-Transversalite.png');

TRUNCATE `cri_competence`;

INSERT INTO `cri_competence` (`id`, `label`, `displayed`, `code_matiere`) VALUES
(1	, 'Prestations sociales', 1, 'A'),
(2	, 'Prestation compensatoire', 1, 'A'),
(3	, 'Acceptation à concurrence de l’actif net (ACAN)', 1, 'A'),
(4	, 'Bénéfice d’inventaire', 1, 'A'),
(5	, 'Communauté légale', 1, 'A'),
(6	, 'Communauté universelle', 1, 'A'),
(7	, 'Compte-joint', 1, 'A'),
(8	, 'Concubinage', 1, 'A'),
(9	, 'Délivrance de legs', 1, 'A'),
(10	, 'Démembrement de propriété', 1, 'A'),
(11	, 'Donations entre époux', 1, 'A'),
(12	, 'Donations entre vifs', 1, 'A'),
(13	, 'Donations-partages', 1, 'A'),
(14	, 'Dons manuels', 1, 'A'),
(15	, 'Envoi en possession', 1, 'A'),
(16	, 'Fonds national de solidarité', 1, 'A'),
(17	, 'Indivision', 1, 'A'),
(18	, 'Legs', 1, 'A'),
(19	, 'Libéralités', 1, 'A'),
(20	, 'Liquidation d’indivisions', 1, 'A'),
(21	, 'Liquidation de communautés', 1, 'A'),
(22	, 'Liquidation de régimes matrimoniaux', 1, 'A'),
(23	, 'Liquidation de successions', 1, 'A'),
(24	, 'Logement de la famille', 1, 'A'),
(25	, 'Mariage', 1, 'A'),
(26	, 'Notoriété', 1, 'A'),
(27	, 'PACS', 1, 'A'),
(28	, 'Participation aux acquêts', 1, 'A'),
(29	, 'Quotité disponible', 1, 'A'),
(30	, 'Rapport', 1, 'A'),
(31	, 'Récompenses', 1, 'A'),
(32	, 'Réduction', 1, 'A'),
(33	, 'Régime primaire', 1, 'A'),
(34	, 'Régimes matrimoniaux ', 1, 'A'),
(35	, 'Remploi', 1, 'A'),
(36	, 'Retour conventionnel', 1, 'A'),
(37	, 'Séparation de biens', 1, 'A'),
(38	, 'Successions ', 1, 'A'),
(39	, 'Testament', 1, 'A'),
(40	, 'Usufruit', 1, 'A'),
(41	, 'Vente entre époux', 1, 'A'),
(42	, 'Adoptions plénière et simple', 1, 'A'),
(43	, 'Filiations légitime et naturelle', 1, 'A'),
(44	, 'Curatelle', 1, 'A'),
(45	, 'Mandat de protection future', 1, 'A'),
(46	, 'Sauvegarde de justice', 1, 'A'),
(47	, 'Sauvegarde de justice', 1, 'A'),
(48	, 'Tutelle', 1, 'A'),
(49	, 'Acte notarié', 1, 'A'),
(50	, 'Action oblique', 1, 'A'),
(51	, 'Action paulienne', 1, 'A'),
(52	, 'Action résolutoire', 1, 'A'),
(53	, 'Adjudication sur licitation', 1, 'A'),
(54	, 'Aide juridictionnelle', 1, 'A'),
(55	, 'Avant-contrat', 1, 'A'),
(56	, 'Bail à nourriture', 1, 'A'),
(57	, 'Bornage', 1, 'A'),
(58	, 'Cadastre – doc d’arpentage', 1, 'A'),
(59	, 'Cession de créance', 1, 'A'),
(60	, 'Chemins d’exploitation', 1, 'A'),
(61	, 'Clause anti-spéculative', 1, 'A'),
(62	, 'Clause pénale', 1, 'A'),
(63	, 'Clause résolutoire', 1, 'A'),
(64	, 'Clauses abusives', 1, 'A'),
(65	, 'Compensation', 1, 'A'),
(66	, 'Complément de part', 1, 'A'),
(67	, 'Conditions pour publier', 1, 'A'),
(68	, 'Conditions suspensive, potestative, résolutoire', 1, 'A'),
(69	, 'Confusion', 1, 'A'),
(70	, 'Construction sur sol d’autrui', 1, 'A'),
(71	, 'Contribution de sécurité immobilière', 1, 'A'),
(72	, 'Copies exécutoires', 1, 'A'),
(73	, 'Dation', 1, 'A'),
(74	, 'Déclaration d’insaisissabilité', 1, 'A'),
(75	, 'Délégation', 1, 'A'),
(76	, 'Délivrance', 1, 'A'),
(77	, 'Démarchage', 1, 'A'),
(78	, 'Dépôt et séquestre', 1, 'A'),
(79	, 'Droit d’auteur ', 1, 'A'),
(80	, 'Droit d’usage et d’habitation', 1, 'A'),
(81	, 'Droit de préemption indivisaire', 1, 'A'),
(82	, 'Echange', 1, 'A'),
(83	, 'Empiètement', 1, 'A'),
(84	, 'Faculté de rétractation', 1, 'A'),
(85	, 'Garantie éviction', 1, 'A'),
(86	, 'Indivision forcée', 1, 'A'),
(87	, 'Indivision', 1, 'A' ),
(88	, 'Interdiction d’aliéner', 1, 'A'),
(89	, 'Interdiction d’instrumenter', 1, 'A'),
(90	, 'Interprétation des conventions', 1, 'A'),
(91	, 'Lésion', 1, 'A'),
(92	, 'Licitation', 1, 'A'),
(93	, 'Loi Hamon', 1, 'A'),
(94	, 'Lois Scrivener', 1, 'A'),
(95	, 'Mandat', 1, 'A'),
(96	, 'Mitoyenneté', 1, 'A'),
(97	, 'Monopole bancaire', 1, 'A'),
(98	, 'Nature des biens', 1, 'A'),
(99	, 'Novation', 1, 'A'),
(100,	'Nullité, résolution, tacite reconduction', 1, 'A'),
(101,	'Pacte de préférence ', 1, 'A'),
(102,	'Paiement', 1, 'A'),
(103,	'Pari passu', 1, 'A'),
(104,	'Partage', 1, 'A'),
(105,	'Porte fort', 1, 'A'),
(106,	'Prescription acquisitive', 1, 'A'),
(107,	'Prescription extinctive ', 1, 'A'),
(108,	'Prêt ', 1, 'A'),
(109,	'Prêt à usage ou commodat', 1, 'A'),
(110,	'Prêt viager hypothécaire', 1, 'A'),
(111,	'Preuve', 1, 'A'),
(112,	'Promesse de vente', 1, 'A'),
(113,	'Propriété, accession', 1, 'A'),
(114,	'Quittance', 1, 'A'),
(115,	'Reconnaissance de dette', 1, 'A'),
(116,	'Rejet, refus', 1, 'A'),
(117,	'Réméré', 1, 'A'),
(118,	'Remise de dette', 1, 'A'),
(119,	'Renonciation à accession', 1, 'A'),
(120,	'Rente viagère', 1, 'A'),
(121,	'Responsabilité', 1, 'A'),
(122,	'Responsabilité bancaire', 1, 'A'),
(123,	'Responsabilité notariale', 1, 'A'),
(124,	'Rétablissement personnel', 1, 'A'),
(125,	'Salaire conservateur', 1, 'A'),
(126,	'Secret professionnel', 1, 'A'),
(127,	'Servitudes', 1, 'A'),
(128,	'Solidarité', 1, 'A'),
(129,	'Subrogation', 1, 'A'),
(130,	'Surendettement', 1, 'A'),
(131,	'TEG', 1, 'A'),
(132,	'Tontine - Clause d’accroissement ', 1, 'A'),
(133,	'Transaction', 1, 'A'),
(134,	'Usufruit, droit d’usage', 1, 'A'),
(135,	'Usure', 1, 'A'),
(136,	'Vente d’immeuble ', 1, 'A'),
(137,	'Viager', 1, 'A'),
(138,	'Vices cachés', 1, 'A'),
(139,	'Vices du consentement', 1, 'A'),
(140,	'Agrasc', 1, 'A'),
(141,	'Antichrèse', 1, 'A'),
(142,	'Appel', 1, 'A'),
(143,	'Avis à tiers détenteur (ATD) , recouvrement fiscal', 1, 'A'),
(144,	'Blanchiment', 1, 'A'),
(145,	'Cassation', 1, 'A'),
(146,	'Cautionnement', 1, 'A'),
(147,	'Cession d’antériorité', 1, 'A'),
(148,	'Compétence d’attribution et territoriale ', 1, 'A'),
(149,	'Confiscation', 1, 'A'),
(150,	'Convention de rang', 1, 'A'),
(151,	'Droit local Alsace Moselle ', 1, 'A'),
(152,	'Fiducie', 1, 'A'),
(153,	'Gage', 1, 'A'),
(154,	'Garantie 1ère demande', 1, 'A'),
(155,	'Hypothèques et privilèges', 1, 'A'),
(156,	'Mainlevées', 1, 'A'),
(157,	'Nantissement de créance, d’assurance, d’instruments financiers, cession Dailly', 1, 'A'),
(158,	'Opposition (sauf en matière de fonds de commerce)', 1, 'A'),
(159,	'Pacte commissoire', 1, 'A'),
(160,	'Partage judiciaire (Droit personnel) ', 1, 'A'),
(161,	'Pénal', 1, 'A'),
(162,	'Purge des hypothèques', 1, 'A'),
(163,	'Recouvrement pensions alimentaires et prestation compensatoire', 1, 'A'),
(164,	'Répartition ou distribution du prix (sauf fonds de commerce)', 1, 'A'),
(165,	'Réserve de propriété', 1, 'A'),
(166,	'Saisie immobilière :  vente amiable autorisée et vente forcée (adjudication)', 1, 'A'),
(167,	'Saisie pénale', 1, 'A'),
(168,	'Saisie-conservatoire, saisie-attribution', 1, 'A'),
(169,	'Tierce opposition', 1, 'A'),
(170,	'Tracfin', 1, 'A'),
(171,	'Translation d’hypothèque', 1, 'A');
