ALTER TABLE `cri_competence` CHANGE `id` `id` VARCHAR(50) NOT NULL; 
ALTER TABLE `cri_competence` ADD COLUMN `short_label` VARCHAR(255) NULL AFTER `label`;

INSERT INTO `cri_competence` (`id`, `label`, `short_label`, `code_matiere`, `displayed` ) VALUES 
('A', "Famille", "Famille", 'A', 1),
('B', "Commercial", "Commercial", 'B', 1),
('C', "Société", "Société", 'C', 1),
('D', "Construction", "Construction", 'D', 1),
('E', "Fiscalité", "Fiscalité", 'E', 1),
('F', "Droit international privé", "Droit international privé", 'F', 1),
('G', "Rural", "Rural", 'G', 1),
('H', "Social-Travail", "Social-Travail", 'H', 1),
('I', "Environnement", "Environnement", 'I', 1),
('K', "Documentation", "Documentation", 'K', 1),
('L', "Droit administratif", "Droit administratif", 'L', 1),
('O', "Obligations", "Obligations", 'O', 1),
('P', "Procédure", "Procédure", 'P', 1),
('1', "Formation ", "Couples : Concubinage, PACS, mariage", 'A', 1),
('2', "Rédaction des différents contrats (rédaction du pacs et contrat de mariage)", "Couples : Concubinage, PACS, mariage", 'A', 1),
('3', "Fonctionnement et liquidation des différents régimes", "Couples : Concubinage, PACS, mariage", 'A', 1),
('4', "Séparation de corps", "Séparation des couples", 'A', 1),
('5', "Divorce, sauf procédure civile", "Séparation des couples", 'A', 1),
('6', "Les différentes procédures  ", "Séparation des couples", 'A', 1),
('7', "Les mesures provisoires", "Séparation des couples", 'A', 1),
('8', "Prestations compensatoires", "Séparation des couples", 'A', 1),
('9', "Les conventions de divorce", "Séparation des couples", 'A', 1),
('10', "Dissolution du PACS", "Séparation des couples", 'A', 1),
('11', "Filiation et adoption", "État des personnes", 'A', 1),
('12', "Aliments", "État des personnes", 'A', 1),
('13', "Nom", "État des personnes", 'A', 1),
('14', "État civil", "État des personnes", 'A', 1),
('15', "Absence", "État des personnes", 'A', 1),
('16', "Mineurs, majeurs protégés, mandat de protection future …", "Incapacités", 'A', 1),
('17', "Donation, donation partage, testament, testament partage, donation entre époux", "Libéralités", 'A', 1),
('18', "Indivision en droit patrimonial de la famille", "Indivision/Partage", 'A', 1),
('19', "Partage amiable ou judiciaire, sauf procédure civile", "Indivision/Partage", 'A', 1),
('20', "Dévolution", "Successions", 'A', 1),
('21', "Passif successoral / Successions vacantes / ACAN", "Successions", 'A', 1),
('22', "Usufruit (aspects successoraux) ", "Successions", 'A', 1),
('23', "Assurances vie (aspects successoraux)", "Successions", 'A', 1),
('24', "Liquidation des successions", "Successions", 'A', 1),
('25', "Recours sur succession …", "Aide sociale", 'A', 1),
('26', "Transmission des concessions funéraires", "Concessions funéraires", 'A', 1),
('27', "Accords collectifs, vente à la découpe, vente par lots", "Baux habitations", 'B', 1),
('28', "Bail loi 1er septembre 1948", "Baux habitations", 'B', 1),
('29', "Bail loi 1989 – loi Alur", "Baux habitations", 'B', 1),
('30', "Droits de préemption", "Baux habitations", 'B', 1),
('31', "Loi Aurillac (droit de la construction + bail habitation)", "Baux habitations", 'B', 1),
('32', "Commissions d’agences immobilières", "Baux habitations", 'B', 1),
('33', "Fonds spéciaux/activités règlementées (taxis)", "Fonds de commerce", 'B', 1),
('34', "Pharmacie", "Fonds de commerce", 'B', 1),
('35', "Registre du commerce et des sociétés", "Fonds de commerce", 'B', 1),
('36', "Statut des artisans (répertoire des métiers)", "Fonds de commerce", 'B', 1),
('37', "Propriété industrielle", "", 'B', 1),
('38', "Moyens de paiement", "Droit bancaire", 'B', 1),
('39', "Fonctionnement des comptes bancaires (manque de compétences)", "Droit bancaire", 'B', 1),
('40', "Agents commerciaux", "", 'B', 1),
('41', "Baux commerciaux", "", 'B', 1),
('42', "Baux professionnels", "", 'B', 1),
('43', "Statuts professionnels", "Clientèle civiles et professions libérales", 'B', 1),
('44', "Baux civils", "", 'B', 1),
('45', "Déclarations d’insaisissabilité – Eirl", "Procédures collectives", 'B', 1),
('46', "Faillite, banqueroute", "Procédures collectives", 'B', 1),
('47', "Liquidation judiciaire / liquidation des biens", "Procédures collectives", 'B', 1),
('48', "Loi 1967 ", "Procédures collectives", 'B', 1),
('49', "Loi 1985 ", "Procédures collectives", 'B', 1),
('50', "Redressement ou règlement judiciaire et procédure de sauvegarde ", "Procédures collectives", 'B', 1),
('51', "Statuts des sociétés", "Création de la société", 'C', 1),
('52', "Apports en capital, mobiliers / immobiliers", "Création de la société", 'C', 1),
('53', "Droits d’enregistrement", "Création de la société", 'C', 1),
('54', "Plus value", "Création de la société", 'C', 1),
('55', "Décès des actionnaires", "Fonctionnement des sociétés", 'C', 1),
('56', "Cessions de parts (entre vifs)", "Fonctionnement des sociétés", 'C', 1),
('57', "Changement de dirigeant", "Fonctionnement des sociétés", 'C', 1),
('58', "Clauses d’agrément", "Fonctionnement des sociétés", 'C', 1),
('59', "Augmentation, diminution de capital", "Fonctionnement des sociétés", 'C', 1),
('60', "Formalités liées au changement d’actionnaires", "Fonctionnement des sociétés", 'C', 1),
('61', "Modification de statut, transformation de sociétés", "Fonctionnement des sociétés", 'C', 1),
('62', "Opérations de dissolution, liquidation, partage", "Disparition des entreprises", 'C', 1),
('63', "PPR", "Urbanisme ", 'D', 1),
('64', "Certificat urbanisme", "Urbanisme ", 'D', 1),
('65', "Construction zone agricole", "Urbanisme ", 'D', 1),
('66', "Contentieux urbanisme Civil/Pénal Adm", "Urbanisme ", 'D', 1),
('67', "Droits préemptions urbains (DPU/ZAD/ENS)", "Urbanisme ", 'D', 1),
('68', "Lotissement Servitude en lotissement", "Urbanisme ", 'D', 1),
('69', "Permis de construire", "Urbanisme ", 'D', 1),
('70', "Doc. D'urbanisme POS - PLU RNU SCOT", "Urbanisme ", 'D', 1),
('71', "Servitude de cour commune", "Urbanisme ", 'D', 1),
('72', "Urbanisme commercial (CDAC)", "Urbanisme ", 'D', 1),
('73', "ZAC", "Urbanisme ", 'D', 1),
('74', "Diagnostics (Amiante, DPE, Electricité, Gaz, Plomb, Mérule, Assainissement)", "Diagnostic", 'D', 1),
('75', "Associations syndicales", "Droit des sols", 'D', 1),
('76', "Cadastre – doc d’arpentage", "Droit des sols", 'D', 1),
('77', "Construction sur sol d’autrui", "Droit des sols", 'D', 1),
('78', "Copropriété", "Copropriété", 'D', 1),
('79', "Droit de préemption Loi 31/12/1975 + Aurillac", "Copropriété", 'D', 1),
('80', "Volumes", "Copropriété", 'D', 1),
('81', "Etablissement Recevant du Public", "", 'D', 1),
('82', "SRU rétractation", "", 'D', 1),
('83', "Contrat de construction maisons individuelles", "CONSTRUCTION", 'D', 1),
('84', "Contrat promotion immobilière", "CONSTRUCTION", 'D', 1),
('85', "Multipropriété", "CONSTRUCTION", 'D', 1),
('86', "Société d’attribution", "CONSTRUCTION", 'D', 1),
('87', "Société de construction/Vente", "CONSTRUCTION", 'D', 1),
('88', "Vente d’immeuble à construire (VEFA)", "CONSTRUCTION", 'D', 1),
('89', "Vente d’immeuble à rénover", "CONSTRUCTION", 'D', 1),
('90', "Bail à construction", "BAC/CB     ", 'D', 1),
('91', "Bail emphytéotique", "BAC/CB     ", 'D', 1),
('92', "Crédit-bail immobilier", "BAC/CB     ", 'D', 1),
('93', "Accession sociale", "HLM", 'D', 1),
('94', "HLM", "HLM", 'D', 1),
('95', "Location accession", "HLM", 'D', 1),
('96', "Logement conventionné", "HLM", 'D', 1),
('97', "PLA", "HLM", 'D', 1),
('98', "PLS", "HLM", 'D', 1),
('99', "Assurances construction ", "RESPONSABILITE DES CONSTRUCTEURS", 'D', 1),
('100', "Responsabilité des constructeurs", "RESPONSABILITE DES CONSTRUCTEURS", 'D', 1),
('101', "Succession / donation / partage", "Droit de l’enregistrement (fiscalité notariale)", 'E', 1),
('102', "Gestion de patrimoine", "Droit de l’enregistrement (fiscalité notariale)", 'E', 1),
('103', "Vente d’immeubles", "Droit de l’enregistrement (fiscalité notariale)", 'E', 1),
('104', "Enregistrement international / fiscalité internationale", "Droit de l’enregistrement (fiscalité notariale)", 'E', 1),
('105', "TVA immobilière", "Fiscalité immobilière", 'E', 1),
('106', "Plus value immobilière /Plus value mobilière", "Fiscalité immobilière", 'E', 1),
('107', "Conséquences fiscales de la transmission", "Fiscalité des entreprises", 'E', 1),
('108', "Fiscalité des bénéfices d’une entreprise (BIC / IS / BNC)", "Fiscalité des entreprises", 'E', 1),
('109', "Plus values professionnelles", "Fiscalité des entreprises", 'E', 1),
('110', "TVA générale", "Fiscalité des entreprises", 'E', 1),
('111', "ISF", "", 'E', 1),
('112', "Défiscalisation immobilière", "IRPP", 'E', 1),
('113', "Revenus fonciers", "IRPP", 'E', 1),
('114', "Revenus mobiliers", "IRPP", 'E', 1),
('115', "Impôts locaux", "", 'E', 1),
('116', "Location en meublé", "", 'E', 1),
('117', "Fiscalité directe agricole ", "", 'E', 1),
('118', "Enregistrement", "Fiscalité internationale", 'E', 1),
('119', "Plus value immobilières", "Fiscalité internationale", 'E', 1),
('120', "Impôts directs", "Fiscalité internationale", 'E', 1),
('121', "Blanchiment d’argent", "investissements internationaux", 'F', 1),
('122', "Acquisition / perte de nationalité", "Condition des étrangers / nationalité", 'F', 1),
('123', "Biens et droits réels", "Obligations internationales", 'F', 1),
('124', "Certifications/légalisations de signature", "Pratique notariale internationale", 'F', 1),
('125', "Commerçants étrangers", "Condition des étrangers / nationalité", 'F', 1),
('126', "Connaissance des réseaux de juristes étrangers / animation", "", 'F', 1),
('127', "Contrats de vente, de prêt, de garantie", "Obligations internationales", 'F', 1),
('128', "Filiation Internationale : reconnaissance, établissement, conséquence et contestation,PMA/GPA, adoption", "Filiation / adoption internationales", 'F', 1),
('129', "Incapacités en droit patrimonial de la famille (mineurs, majeurs, tutelles…)", "incapacités internationales", 'F', 1),
('130', "Les personnes physiques et morales : existence et attribut, état civil, … ", "Statut personnel avec un élément d'extranéité", 'F', 1),
('131', "Mandats ", "Obligations internationales", 'F', 1),
('132', "Procurations", "Pratique notariale internationale", 'F', 1),
('133', "Publicité foncière / Obligations internationales", "Obligations internationales", 'F', 1),
('134', "Publicité foncière / Pratique notariale internationale", "Pratique notariale internationale", 'F', 1),
('135', "Qualification des actes étrangers …", "Pratique notariale internationale", 'F', 1),
('136', "Reconnaissance et exécution des actes authentiques et des décisions judiciaires (jugements de divorce, en matière de filiation, …)", "Circulation des actes et jugements étrangers et à l'étranger", 'F', 1),
('137', "Sociétés étrangères et sociétés française à l'étranger", "Sociétés avec un élement d'extranéité", 'F', 1),
('138', "Titre de séjour", "Condition des étrangers / nationalité", 'F', 1),
('139', "Titre exécutoire européen (TEE)", "Obligations internationales", 'F', 1),
('140', "Tous les aspects civils", "Droit comparé", 'F', 1),
('141', "Tous les aspects civils des régimes matrimoniaux internationaux (détermination, changement, dissolution)", "Régimes matrimoniaux  internationaux", 'F', 1),
('142', "Tous les aspects civils d'une succession internationale (planification, loi applicable, compétence notariale, contentieux, …)", "Successions internationales", 'F', 1),
('143', "Transfert de capitaux", "Relations financières internationales", 'F', 1),
('144', "Trust", "Obligations internationales", 'F', 1),
('145', "Fonctionnement / attribution", "SAFER", 'G', 1),
('146', "Droit de préemption SAFER", "SAFER", 'G', 1),
('147', "Bail à ferme, bail à métayage, baux à long terme, bail cessible hors cadre familial", "BAUX RURAUX", 'G', 1),
('148', "Autres Conventions : baux emphytéotiques / conventions de mise à disposition / baux de petites parcelles / prêts à usage gratuit (immeubles ruraux)…", "BAUX RURAUX", 'G', 1),
('149', "Contrôle des structures (exploitation des terres)", "", 'G', 1),
('150', "Remembrements ruraux (aménagement foncier agricole)", "", 'G', 1),
('151', "Sociétés et groupements agricoles : caractéristiques et conseils à la mise en place", "", 'G', 1),
('152', "Coopératives agricoles", "", 'G', 1),
('153', "Fonds agricoles", "", 'G', 1),
('154', "Viticulture (baux, sociétés)", "", 'G', 1),
('155', "Pêche et chasse (baux…)", "", 'G', 1),
('156', "Activités équestres", "", 'G', 1),
('157', "Cotisations sociales MSA : assurances sociales/ retraite", "", 'G', 1),
('158', "Politique agricole commune", "", 'G', 1),
('159', "Aides aux agriculteurs", "", 'G', 1),
('160', "Succession d’un exploitant (transmission de l’exploitation/salaire différé / attribution préférentielle)", "", 'G', 1),
('161', "Droits à production (droits de plantation ou de replantation)", "", 'G', 1),
('162', "Echanges d’immeubles ruraux", "", 'G', 1),
('163', "Etangs (droit de l’eau)", "", 'G', 1),
('164', "Particularités fiscales agricoles (plus values, droits d’enregistrement, TVA, impôt sur le revenu)", "FISCALITE AGRICOLE", 'G', 1),
('165', "Défrichement", "DROIT FORESTIER ET FISCALITE FORESTIERE", 'G', 1),
('166', "Droits de préférence et de préemption forestier", "DROIT FORESTIER ET FISCALITE FORESTIERE", 'G', 1),
('167', "Sociétés spécifiques au milieu forestier", "DROIT FORESTIER ET FISCALITE FORESTIERE", 'G', 1),
('168', "Particularités fiscales propres à la forêt (plus value, droit d’enregistrement, TVA, impôt sur le revenu)", "DROIT FORESTIER ET FISCALITE FORESTIERE", 'G', 1),
('169', "Droit de l’eau", "Droit de l’environnement", 'I', 1),
('170', "Droit des installations classées pour la protection de l’environnement/déchets", "Droit de l’environnement", 'I', 1),
('171', "Droit des sols pollués", "Droit de l’environnement", 'I', 1),
('172', "Fonctionnement des collectivités publiques/ Intercommunalité", "", 'L', 1),
('173', "Acquisitions", "Patrimoine des collectivités publiques", 'L', 1),
('174', "Aliénations", "Patrimoine des collectivités publiques", 'L', 1),
('175', "Echanges", "Patrimoine des collectivités publiques", 'L', 1),
('176', "Baux", "Patrimoine des collectivités publiques", 'L', 1),
('177', "Contrats spécifiques au domaine public", "Patrimoine des collectivités publiques", 'L', 1),
('178', "Patrimoine public hospitalier", "", 'L', 1),
('179', "Libéralités aux personnes publiques", "", 'L', 1),
('180', "Biens vacants et sans maître ", "", 'L', 1),
('181', "Aides aux entreprises ", "Interventionnisme économique", 'L', 1),
('182', "SEML/ SPL /SPLA", "Interventionnisme économique", 'L', 1),
('183', "Concession", "Gestion du service public", 'L', 1),
('184', "Affermage", "Gestion du service public", 'L', 1),
('185', "Régie", "Gestion du service public", 'L', 1),
('186', "Marchés publics /Commande publique ", "", 'L', 1),
('187', "Comptabilité publique", "", 'L', 1),
('188', "Expropriation", "", 'L', 1),
('189', "Fonction publique", "", 'L', 1),
('190', "Contentieux administratif", "", 'L', 1),
('191', "Responsabilité administrative", "", 'L', 1),
('192', "Servitude d’utilité publique", "", 'L', 1),
('193', "Gestion du cimetière", "Législation funéraire", 'L', 1),
('194', "Gestion des concessions funéraires", "Législation funéraire", 'L', 1),
('195', "Voies publiques", "Droit de la voirie", 'L', 1),
('196', "Chemins ruraux", "Droit de la voirie", 'L', 1),
('197', "Associations(Loi 1901/loi 1905) sauf associations syndicales", "Groupements divers", 'L', 1),
('198', "Fondations", "Groupements divers", 'L', 1),
('199', "Fonds de dotation ", "Groupements divers", 'L', 1),
('200', "Congrégations", "Groupements divers", 'L', 1),
('201', "Syndicats professionnels", "Groupements divers", 'L', 1),
('202', "Mutuelles", "Groupements divers", 'L', 1),
('203', "Succession vacante – succession acceptée sous bénéfice d’inventaire et/ou à concurrence de l’actif net", "", 'O', 1),
('204', "Avant-contrats de vente (promesse de vente synallagmatique ou unilatérale)", "Contrat de vente", 'O', 1),
('205', "Droit de la vente y compris vente en viager", "Contrat de vente", 'O', 1),
('206', "Pacte de préférence ", "Contrat de vente", 'O', 1),
('207', "Financement : droit du crédit, monopole bancaire, responsabilité bancaire, garanties, sûretés (hypothèque, privilège, cautionnement, nantissement)", "Droit du crédit et sûretés", 'O', 1),
('208', "Lois Scrivener, TEG, usure, surendettement, rétablissement personnel, délai de réflexion ou rétraction, clauses abusives ", "Droit de la consommation", 'O', 1),
('209', "Droit de la publicité foncière / Cadastre", "", 'O', 1),
('210', "Impact du régime matrimonial, de l’indivision, du pacs, droit des sociétés …", "", 'O', 1),
('211', "Echange", "Contrats divers", 'O', 1),
('212', "Bail à nourriture", "Contrats divers", 'O', 1),
('213', "Commodat", "Contrats divers", 'O', 1),
('214', "Dation", "Contrats divers", 'O', 1),
('215', "Dépôt et séquestre", "Contrats divers", 'O', 1),
('216', "Procuration (mandat)", "Contrats divers", 'O', 1),
('217', "Transaction", "Contrats divers", 'O', 1),
('218', "Tontine", "Contrats divers", 'O', 1),
('219', "Contrat de fortage", "Contrats divers", 'O', 1),
('220', "Conditions suspensives et résolutoires", "Droit des obligations", 'O', 1),
('221', "Action paulienne", "Droit des obligations", 'O', 1),
('222', "Modes de paiement, compensation, confusion …", "Droit des obligations", 'O', 1),
('223', "Prescription extinctive, remise de dette, quittance, solidarité", "Droit des obligations", 'O', 1),
('224', "Subrogation, novation, cession de créance, délégation", "Droit des obligations", 'O', 1),
('225', "Régime de la preuve", "Droit des obligations", 'O', 1),
('226', "Caducité, nullité, résolution", "Droit des obligations", 'O', 1),
('227', "Partage judiaciaire", "", 'O', 1),
('228', "Démembrement de propriété / usufruit / droit d’usage", "Droit des biens", 'O', 1),
('229', "Indivision", "Droit des biens", 'O', 1),
('230', "Servitudes, chemin d’exploitation, indivision forcée, mitoyenneté", "Droit des biens", 'O', 1),
('231', "Accession, droit de propriété, prescription acquisitive", "Droit des biens", 'O', 1),
('232', "Propriété littéraire et artistique", "Droit des biens", 'O', 1),
('233', "Formalisme de l’acte notarié,", "Droit notarial", 'O', 1),
('234', "Responsabilité notariale", "Droit notarial", 'O', 1),
('235', "Secret professionnel", "Droit notarial", 'O', 1),
('236', "Déontologie", "Droit notarial", 'O', 1),
('237', "Vente forcée", "", 'O', 1),
('238', "Avis tiers détenteur, opposition, régimes spéciaux", "", 'O', 1),
('239', "Déclaration d’insaisissabilité", "", 'O', 1),
('240', "Droit local Alsace Moselle", "", 'O', 1),
('241', "Appel, pourvoi, tierce opposition, aide juridictionnelle …", "Procédure civile", 'P', 1),
('242', "Saisie immobilière", "Voies d’exécution", 'P', 1),
('243', "Saisies mobilières (saisie attribution, saisie conservatoire, saisie vente …)", "Voies d’exécution", 'P', 1),
('244', "Blanchiment et plus generalement droit pénal", "", 'P', 1);