ALTER TABLE `cri_competence` CHANGE `id` `id` VARCHAR(50) NOT NULL; 
ALTER TABLE `cri_competence` ADD COLUMN `short_label` VARCHAR(255) NULL AFTER `label`;

INSERT INTO `cri_competence` (`id`, `label`, `short_label`, `code_matiere`, `displayed` ) VALUES 
('A', "Famille", "Famille", 'A', 1),
('B', "Commercial", "Commercial", 'B', 1),
('C', "Société", "Société", 'C', 1),
('D', "Construction", "Construction", 'D', 1),
('E', "Fiscalité", "Fiscalité", 'E', 1),
('F', "Droit international privé", "Droit international privé", 'F', 1),
('G', "Rural", "Rural", 'G', 1),
('H', "Social-Travail", "Social-Travail", 'H', 1),
('I', "Environnement", "Environnement", 'I', 1),
('K', "Documentation", "Documentation", 'K', 1),
('L', "Droit administratif", "Droit administratif", 'L', 1),
('O', "Obligations", "Obligations", 'O', 1),
('P', "Procédure", "Procédure", 'P', 1),
(1, "Formation ", "Couples", 'A', 1),
(2, "Rédaction des dfts contrats", "Couples", 'A', 1),
(3, "Fct et liquid dfts régimes", "Couples", 'A', 1),
(4, "Séparation de corps", "Sépara coupl", 'A', 1),
(5, "Divorce, sauf procédure civile", "Sépara coupl", 'A', 1),
(6, "Les différentes procédures", "Sépara coupl", 'A', 1),
(7, "Les mesures provisoires", "Sépara coupl", 'A', 1),
(8, "Prestations compensatoires", "Sépara coupl", 'A', 1),
(9, "Les conventions de divorce", "Sépara coupl", 'A', 1),
(10, "Dissolution du PACS", "Sépara coupl", 'A', 1),
(11, "Filiation et adoption", "Etat des per", 'A', 1),
(12, "Aliments", "Etat des per", 'A', 1),
(13, "Nom", "Etat des per", 'A', 1),
(14, "État civil", "Etat des per", 'A', 1),
(15, "Absence", "Etat des per", 'A', 1),
(16, "Min/majeurs pro, protec future", "Incapacités", 'A', 1),
(17, "Don,testamt/partage,don époux", "", 'A', 1),
(18, "Indivis Dt patrimo de famille", "Indiv/partag", 'A', 1),
(19, "Partage amiable/judici,sauf PC", "Dt crédits", 'A', 1),
(20, "Dévolution", "Successions", 'A', 1),
(21, "Passif successo/Succe vac/ACAN", "Successions", 'A', 1),
(22, "Usufruit aspects successoraux", "Successions", 'A', 1),
(23, "Assurance vie : aspect success", "Successions", 'A', 1),
(24, "Liquidation des successions", "Successions", 'A', 1),
(25, "Recours sur succession", "Aide sociale", 'A', 1),
(26, "Transmiss concess funéraires", "Co funéraire", 'A', 1),
(27, "Acrd collec,vente découpe/lots", "Baux habita", 'B', 1),
(28, "Bail loi 1er septembre 1948", "Baux habita", 'B', 1),
(29, "Bail loi 1989 - loi Alur", "Baux habita", 'B', 1),
(30, "Droits de préemption", "Baux habita", 'B', 1),
(31, "Loi Aurillac : Dt constru+bail", "Baux habita", 'B', 1),
(32, "Commissions d'agences immo", "Baux habita", 'B', 1),
(33, "Fonds spé/activté régl. (taxi)", "Fonds commer", 'B', 1),
(34, "Pharmacie", "Fonds commer", 'B', 1),
(35, "Registre commerce et sociétés", "Fonds commer", 'B', 1),
(36, "Statut artisans (rép. métiers)", "Fonds commer", 'B', 1),
(37, "Propriété industrielle", "", 'B', 1),
(38, "Moyens de paiement", "Dt bancaire", 'B', 1),
(39, "Fct compte ban (manque compét)", "Dt bancaire", 'B', 1),
(40, "Agents commerciaux", "", 'B', 1),
(41, "Baux commerciaux", "", 'B', 1),
(42, "Baux professionnels", "", 'B', 1),
(43, "Statuts professionnels", "Client civ", 'B', 1),
(44, "Baux civils", "", 'B', 1),
(45, "Déclar insaisissabilité -Eirl", "Procé collec", 'B', 1),
(46, "Faillite, banqueroute", "Procé collec", 'B', 1),
(47, "Liq judiciaire/liq biens", "Procé collec", 'B', 1),
(48, "Loi 1967 ", "Procé collec", 'B', 1),
(49, "Loi 1985 ", "Procé collec", 'B', 1),
(50, "Redresse/règlt ju & procé sauv", "Procé collec", 'B', 1),
(51, "PPR", "Urbanisme", 'D', 1),
(52, "Certificat urbanisme", "Urbanisme", 'D', 1),
(53, "Construction zone agricole", "Urbanisme", 'D', 1),
(54, "Contentieux urba Civ/Pénal Adm", "Urbanisme", 'D', 1),
(55, "Dt préempt urba (DPU/ZAD/ENS)", "Urbanisme", 'D', 1),
(56, "Lotissement et Servitude", "Urbanisme", 'D', 1),
(57, "Permis de construire", "Urbanisme", 'D', 1),
(58, "Doc. d'urba POS - PLU RNU SCOT", "Urbanisme", 'D', 1),
(59, "Servitude de cour commune", "Urbanisme", 'D', 1),
(60, "Urbanisme commercial (CDAC)", "Urbanisme", 'D', 1),
(61, "ZAC", "Urbanisme", 'D', 1),
(62, "Diagnostics (Amiante,Gaz,...)", "Diagnostic", 'D', 1),
(63, "Associations syndicales", "Dt des sols", 'D', 1),
(64, "Cadastre - doc d'arpentage", "Dt des sols", 'D', 1),
(65, "Construction sur sol d'autrui", "Dt des sols", 'D', 1),
(66, "Copropriété", "Copropriété", 'D', 1),
(67, "Préemption:31/12/1975+Aurillac", "Copropriété", 'D', 1),
(68, "Volumes", "Copropriété", 'D', 1),
(69, "Etablissement Recevant Public", "", 'D', 1),
(70, "SRU rétractation", "", 'D', 1),
(71, "Contrat constru maisons indiv", "Construction", 'D', 1),
(72, "Contrat promotion immobilière", "Construction", 'D', 1),
(73, "Multipropriété", "Construction", 'D', 1),
(74, "Société d'attribution", "Construction", 'D', 1),
(75, "Société de construction/vente", "Construction", 'D', 1),
(76, "Vente immeubl construire(VEFA)", "Construction", 'D', 1),
(77, "Vente d'immeuble à rénover", "Construction", 'D', 1),
(78, "Bail à construction", "BAC/CB", 'D', 1),
(79, "Bail emphytéotique", "BAC/CB", 'D', 1),
(80, "Crédit-bail immobilier", "BAC/CB", 'D', 1),
(81, "Accession sociale", "HLM", 'D', 1),
(82, "HLM", "HLM", 'D', 1),
(83, "Location accession", "HLM", 'D', 1),
(84, "Logement conventionné", "HLM", 'D', 1),
(85, "PLA", "HLM", 'D', 1),
(86, "PLS", "HLM", 'D', 1),
(87, "Assurances construction ", "Respon const", 'D', 1),
(88, "Responsabilité constructeurs", "Respon const", 'D', 1),
(89, "Succession/donation/partage", "Dt enregistr", 'E', 1),
(90, "Gestion de patrimoine", "Dt enregistr", 'E', 1),
(91, "Vente d'immeubles", "Dt enregistr", 'E', 1),
(92, "Enregistrement/fisc internatio", "Dt enregistr", 'E', 1),
(93, "TVA immobilière", "Fisca immo", 'E', 1),
(94, "Plus value im/mobilières", "Fisca immo", 'E', 1),
(95, "Conséq fiscales de la transmis", "Fisca entrep", 'E', 1),
(96, "Fisc bénéf ENT (BIC/IS/BNC)", "Fisca entrep", 'E', 1),
(97, "Plus values professionnelles", "Fisca entrep", 'E', 1),
(98, "TVA générale", "Fisca entrep", 'E', 1),
(99, "ISF", "", 'E', 1),
(100, "Défiscalisation immobilière", "IRPP", 'E', 1),
(101, "Revenus fonciers", "IRPP", 'E', 1),
(102, "Revenus mobiliers", "IRPP", 'E', 1),
(103, "Impôts locaux", "", 'E', 1),
(104, "Location en meublé", "", 'E', 1),
(105, "Fiscalité directe agricole", "", 'E', 1),
(106, "Enregistrement", "Fisca int", 'E', 1),
(107, "Plus value immobilières", "Fisca int", 'E', 1),
(108, "Impôts directs", "Fisca int", 'E', 1),
(109, "Fonctionnement / attribution", "SAFER", 'G', 1),
(110, "Droit de préemption SAFER", "SAFER", 'G', 1),
(111, "Baux à ferme,etc,hors famille", "Baux ruraux", 'G', 1),
(112, "Autres Conventions", "Baux ruraux", 'G', 1),
(113, "Contrôle structure (terre)", "", 'G', 1),
(114, "Remembrements ruraux (AFA)", "", 'G', 1),
(115, "Stés/groupements agricoles", "", 'G', 1),
(116, "Coopératives agricoles", "", 'G', 1),
(117, "Fonds agricoles", "", 'G', 1),
(118, "Viticulture (baux, sociétés)", "", 'G', 1),
(119, "Pêche et chasse (baux...)", "", 'G', 1),
(120, "Activités équestres", "", 'G', 1),
(121, "Cotisations sociales MSA", "", 'G', 1),
(122, "Politique agricole commune", "P.A.C", 'G', 1),
(123, "Aides aux agriculteurs", "", 'G', 1),
(124, "Succession d'un exploitant", "", 'G', 1),
(125, "Droit à production(plantation)", "", 'G', 1),
(126, "Echanges d'immeubles ruraux", "", 'G', 1),
(127, "Etangs (droit de l'eau)", "", 'G', 1),
(128, "Particularités fisc. agricoles", "Fisc agri", 'G', 1),
(129, "Défrichement", "Dt forestier", 'G', 1),
(130, "Dt préfér. & préempt forestier", "Dt forestier", 'G', 1),
(131, "Stés spé milieu forestier", "Dt forestier", 'G', 1),
(132, "Particularité fisca forestier", "Dt forestier", 'G', 1),
(133, "Statuts des sociétés", "Création soc", 'C', 1),
(134, "Apports capital, im/mobiliers", "Création soc", 'C', 1),
(135, "Droits d'enregistrement", "Création soc", 'C', 1),
(136, "Plus value", "Création soc", 'C', 1),
(137, "Décès des actionnaires", "Fct soc", 'C', 1),
(138, "Cessions de parts (entre vifs)", "Fct soc", 'C', 1),
(139, "Changement de dirigeant", "Fct soc", 'C', 1),
(140, "Clauses d'agrément", "Fct soc", 'C', 1),
(141, "Formalités chgmt actionnaires", "Fct soc", 'C', 1),
(142, "Modif statut, transform  soc", "Fct soc", 'C', 1),
(143, "Augmenta/Diminution capital", "Fct soc", 'C', 1),
(144, "Opération dissol/iquid/partage", "Dispar entre", 'C', 1),
(145, "Aspect civ rég matrimo interna", "Rég mat int", 'F', 1),
(146, "Aspects civ succession interna", "Success int", 'F', 1),
(147, "Incapa Dt patrimonial famille", "Incapa int", 'F', 1),
(148, "Pers. physiques et morales ", "Statut perso", 'F', 1),
(149, "Soc étrang, soc frç à étranger", "Soc Et extra", 'F', 1),
(150, "Fct collecvtés publi/ Intercom", "", 'L', 1),
(151, "Acquisitions", "Patri collec", 'L', 1),
(152, "Aliénations", "Patri collec", 'L', 1),
(153, "Echanges", "Patri collec", 'L', 1),
(154, "Baux", "Patri collec", 'L', 1),
(155, "Contrats spéc domaine public", "Patri collec", 'L', 1),
(156, "Patrimoine public hospitalier", "", 'L', 1),
(157, "Libéralités personne publique", "", 'L', 1),
(158, "Biens vacants et sans maître ", "", 'L', 1),
(159, "Aides aux entreprises ", "Interven éco", 'L', 1),
(160, "SEML/ SPL /SPLA", "Interven éco", 'L', 1),
(161, "Concession", "Gestion S.P", 'L', 1),
(162, "Affermage", "Gestion S.P", 'L', 1),
(163, "Régie", "Gestion S.P", 'L', 1),
(164, "Marchés et commandes publics", "", 'L', 1),
(165, "Comptabilité publique", "", 'L', 1),
(166, "Expropriation", "", 'L', 1),
(167, "Fonction publique", "", 'L', 1),
(168, "Contentieux administratif", "", 'L', 1),
(169, "Responsabilité administrative", "", 'L', 1),
(170, "Servitude d'utilité publique", "", 'L', 1),
(171, "Gestion du cimetière", "Légi funérai", 'L', 1),
(172, "Gestion concessions funéraires", "Légi funérai", 'L', 1),
(173, "Voies publiques", "Dt de voirie", 'L', 1),
(174, "Chemins ruraux", "Dt de voirie", 'L', 1),
(175, "Droit de l'eau", "Dt environ", 'I', 1),
(176, "Dt install protection environ", "Dt environ", 'I', 1),
(177, "Droit des sols pollués", "Dt environ", 'I', 1),
(178, "Assoc sauf assoc syndic", "Grpmt divers", 'L', 1),
(179, "Fondations", "Grpmt divers", 'L', 1),
(180, "Fonds de dotation ", "Grpmt divers", 'L', 1),
(181, "Congrégations", "Grpmt divers", 'L', 1),
(182, "Syndicats professionnels", "Grpmt divers", 'L', 1),
(183, "Mutuelles", "Grpmt divers", 'L', 1),
(184, "Appel, pourvoi, AJ,etc", "Procédu civ", 'P', 1),
(185, "Success vancan bénéf inventair", "", 'O', 1),
(186, "Avant-contrats vente: promesse", "Contrat V", 'O', 1),
(187, "Droit de la vente même viager", "Contrat V", 'O', 1),
(188, "Pacte de préférence", "Contrat V", 'O', 1),
(189, "Financement : droit crédit,...", "Financement", 'O', 1),
(190, "Lois Scrivener, TEG, usure,...", "Droit conso", 'O', 1),
(191, "Dt pub foncière / Cadastre", "", 'O', 1),
(192, "Impacts indivision, pacs,...", "", 'O', 1),
(193, "Blanchiment : plus droit pénal", "", 'P', 1),
(194, "Echange", "Contrat div", 'O', 1),
(195, "Bail à nourriture", "Contrat div", 'O', 1),
(196, "Commodat", "Contrat div", 'O', 1),
(197, "Dation", "Contrat div", 'O', 1),
(198, "Dépôt et séquestre", "Contrat div", 'O', 1),
(199, "Procuration (mandat)", "Contrat div", 'O', 1),
(200, "Transaction", "Contrat div", 'O', 1),
(201, "Tontine", "Contrat div", 'O', 1),
(202, "Contrat de fortage", "Contrat div", 'O', 1),
(203, "Condit. suspens/résolutoires", "Droit obliga", 'O', 1),
(204, "Action paulienne", "Droit obliga", 'O', 1),
(205, "Paiement, compensation,...", "Droit obliga", 'O', 1),
(206, "Quittance, solidarité,...", "Droit obliga", 'O', 1),
(207, "Subrogation, novation,...", "Droit obliga", 'O', 1),
(208, "Régime de la preuve", "Droit obliga", 'O', 1),
(209, "Caducité, nullité, résolution", "Droit obliga", 'O', 1),
(210, "Partage judiaciaire", "", 'O', 1),
(211, "Démembremt propriété,usufruit ", "Droit biens", 'O', 1),
(212, "Indivision", "Droit biens", 'O', 1),
(213, "Servitudes, mitoyenneté...", "Droit biens", 'O', 1),
(214, "Accession, droit propriété...", "Droit biens", 'O', 1),
(215, "Propriété lit. et artistique", "Droit biens", 'O', 1),
(216, "Formalisme de l'acte notarié", "Dt notarial", 'O', 1),
(217, "Responsabilité notariale", "Dt notarial", 'O', 1),
(218, "Secret professionnel", "Dt notarial", 'O', 1),
(219, "Déontologie", "Dt notarial", 'O', 1),
(220, "Saisie immobilière", "Voies exécu", 'P', 1),
(221, "Saisies mobilières", "Voies exécu", 'P', 1),
(222, "Vente forcée", "Dt notarial", 'O', 1),
(223, "Avis tiers détenteur...", "", 'O', 1),
(224, "Déclaration d'insaisissabilité", "", 'O', 1),
(225, "Droit local Alsace Moselle", "", 'O', 1),
(226, "Contrats vente, prêt, garantie", "Obliga int", 'F', 1),
(227, "Mandats ", "Obliga int", 'F', 1),
(228, "Biens et droits réels", "Obliga int", 'F', 1),
(229, "Publicité foncière", "Obliga int", 'F', 1),
(230, "Trust", "Obliga int", 'F', 1),
(231, "Titre exécutoire européen: TEE", "Obliga int", 'F', 1),
(232, "Transfert de capitaux", "Rela fin int", 'F', 1),
(233, "Blanchiment d'argent", "Investi int", 'F', 1),
(234, "Titre de séjour", "Condi étrang", 'F', 1),
(235, "Acquisition /perte nationalité", "Condi étrang", 'F', 1),
(236, "Commerçants étrangers", "Condi étrang", 'F', 1),
(237, "Procurations", "Prtq nota in", 'F', 1),
(238, "Certifi/légalisation signature", "Prtq nota in", 'F', 1),
(239, "Publicité foncière", "Prtq nota in", 'F', 1),
(240, "Qualification actes étrangers", "Prtq nota in", 'F', 1),
(241, "Reconnai, exécu actes/décision", "Actes étrang", 'F', 1),
(242, "Tous les aspects civils", "Dt comparé", 'F', 1),
(243, "Connai juriste étran/animation", "", 'F', 1),
(244, "Filiation Inter, PMA/GPA", "Fil adop int", 'F', 1);