version: "2"

options:
  compose-file-path: './docker-compose.yml'
  compose-dev-file-path: './docker-compose-osx.yml'
  verbose: true # make the whole sync verbose
syncs:
  wpcridon-sync: #tip: add -sync and you keep consistent names als a convention
    src: '../server'
    dest: '/var/www/html'
    sync_strategy: 'unison'
    sync_host_ip: '127.0.0.1'
    sync_host_port: 10872
    sync_user: 'www-data'
    sync_userid: '1000'
    watch_args: '-v' # make fswatch verbose
