version: "2.0"

services:
    web:
        container_name: ${COMPOSE_PROJECT_NAME}-web
        image: registry.jetpulp.fr:5000/dev/php56-apache-oci8
        ports:
            - "${DOCKER_PORT_HTTP}:80"
            - "${DOCKER_PORT_HTTPS}:443"
        volumes:
            - ../server:/var/www/html
            - ./web/vhost.conf:/etc/apache2/sites-enabled/vhost.conf
            - ./web/php.ini:/usr/local/etc/php/php.ini
            - certificat-ssl:/certs
        environment:
            - VIRTUAL_HOST
            - ALLOW_OVERRIDE=true
            - SERVER_NAME
            - USER_UID
            - USER_GROUP
            - DOCKER_HOST_IP
        depends_on:
            - db
            - mailhog
            #- blackfire
            - gulp
    db:
        container_name: ${COMPOSE_PROJECT_NAME}-db
        image: mariadb:10.0
        ports:
            - "${DOCKER_PORT_MYSQL}:3306"
        volumes:
            - ./db:/docker-entrypoint-initdb.d
            - dbdata:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE
    mailhog:
        container_name: ${COMPOSE_PROJECT_NAME}-mailhog
        image: mailhog/mailhog
        ports:
            - "${DOCKER_PORT_MAILHOG}:8025"
    gulp:
        container_name: ${COMPOSE_PROJECT_NAME}-gulp
        image: registry.jetpulp.fr:5000/dev/gulp-dev
        ports:
            - "${DOCKER_PORT_BSYNC}:3000"
            - "${DOCKER_PORT_BSYNC1}:3001"
        volumes:
            - ../server:/app
            - certificat-ssl:/certs
        environment:
            - BUILD_PATH=gulp
            - SERVER_NAME
            - USER_UID
            - USER_GROUP
        dns:
            - 192.168.69.47
    blackfire:
      container_name: ${COMPOSE_PROJECT_NAME}-blackfire
      image: blackfire/blackfire
      environment:
          - BLACKFIRE_SERVER_ID
          - BLACKFIRE_SERVER_TOKEN
    search-replace-db:
        container_name: ${COMPOSE_PROJECT_NAME}-search-replace-db
        image: registry.jetpulp.fr:5000/dev/search-replace-db
        volumes:
            - ./db/config.yml:/app/config.yml
        depends_on:
            - db
        environment:
            - DB_ENV_MYSQL_USER=root
            - DB_ENV_MYSQL_PASSWORD=root
            - DB_ENV_MYSQL_DATABASE=$MYSQL_DATABASE
            - SERVER_NAME

volumes:
  dbdata:
    external:
      name: ${COMPOSE_PROJECT_NAME}-dbdata
  certificat-ssl:
    external: true

networks:
    default:
