web:
    container_name: wp_cridon-web
    image: registry.jetpulp.fr:5000/dev/php56-apache-oci8
    ports:
        - "80:80"
        - "443:443"
    volumes:
        - ../server:/var/www/wp_cridon/server
        - ./web/vhost.conf:/etc/apache2/sites-enabled/vhost.conf
        - ./web/php.ini:/usr/local/etc/php/php.ini
    volumes_from:
          - certificat-ssl
    environment:
        - ALLOW_OVERRIDE=true
        - SERVER_NAME
        - SERVER_NAME_IMAGES
        - SERVER_NAME_STATIC
        - USER_UID
        - USER_GROUP
    links:
        - db:db
        - mailhog:mailhog
#        - blackfire:blackfire
        - gulp:gulp
db:
    container_name: wp_cridon-db
    image: mariadb:10.0
    ports:
        - "3306:3306"
    volumes:
        - ./db:/docker-entrypoint-initdb.d
    volumes_from:
        - wp_cridon-dbdata
    environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE
        - SERVER_NAME
mailhog:
    container_name: wp_cridon-mailhog
    image: mailhog/mailhog
    ports:
        - "8025:8025"
blackfire:
    container_name: blackfire
    image: blackfire/blackfire
    environment:
        - BLACKFIRE_SERVER_ID
        - BLACKFIRE_SERVER_TOKEN
gulp:
    container_name: gulp-dev
    image: registry.jetpulp.fr:5000/dev/gulp-dev
    ports:
        - "3000:3000"
        - "3001:3001"
    volumes:
        - ../server/:/app
    volumes_from:
        - certificat-ssl
    environment:
        - BUILD_PATH=gulp
        - SERVER_NAME
        - USER_UID
        - USER_GROUP
    dns:
        - 192.168.69.47
search-replace-db:
    container_name: search-replace-db
    image: registry.jetpulp.fr:5000/dev/search-replace-db
    volumes:
        - ./db/config.yml:/app/config.yml
    links:
        - db:db
    environment:
        - DB_ENV_MYSQL_USER=root
        - DB_ENV_MYSQL_PASSWORD=root
        - DB_ENV_MYSQL_DATABASE=$MYSQL_DATABASE
        - SERVER_NAME
        - SERVER_NAME_ALIAS
