
set :application, 'wp_cridon'
set :repo_url, 'git@git.jetpulp.hosting:php/wp_cridon.git'

ask :capistrano

# set :deploy_to, '/srv/www/vhosts/TODO'

set :deploy_via, :remote_cache

set :linked_dirs,  [
"server/wp-content/uploads",
"server/wp-content/ewww",
"server/wp-content/wp-rocket-config"
]

set :linked_files, [
"server/wp-config.php",
"server/robots.txt",
"server/.htaccess"
]


#set :copy_exclude, [ ]
# USE .gitattributes file to exclude some files/dirs from deploy

set :keep_releases, 2


# First we need to set some variables so we know where things are. You should
# only have to modify :theme_path here, :local_app_path and :local_server_path
# are set from that.
set :theme_path, Pathname.new('server/wp-content/themes/maestro/library')
set :local_app_path, Pathname.new(File.dirname(__FILE__)).join('../../')
set :local_theme_path, fetch(:local_app_path).join(fetch(:theme_path))
set :local_server_path, Pathname.new(Dir.pwd).join('../server')


# Next we list the production assets we want to deploy,
# theses assets must have been generated by gulp build before
# This build is run in GITLAB-CI, or might by run manually if your run deploy manually
set :production_assets, [
  'css/style.css',
  'css/login.css',
  'css/ie.css',
  'css/front-back-styles.css',
  'css/admin.css',
  'js/min/app.min.js',
  'js/min/scripts.min.js',
  'js/min/slider.min.js',
  'fonts/svgfont',
  'images/sprites/spritesheet.png',
].map {|path| Pathname.new(path) }

namespace :deploy do

  # The :copy_assets task goes through the list of production assets and uploads them to the server. It also creates
  # the target directories if necessary.
  task :copy_assets do
    on roles(:web) do
      fetch(:production_assets).each do |path|
        execute :mkdir, "-p", release_path.join(fetch(:theme_path)).join(path.dirname())
        upload! fetch(:local_theme_path).join(path).to_s, release_path.join(fetch(:theme_path)).join(path), :recursive => true
      end
    end
  end
end

# This tells Capistrano to copy our production assets to the server after it
# has created the release directory but before it has published the release.
before "deploy:updated", "deploy:copy_assets"
